name: Build and Publish Add-on Images

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
            platform: linux/amd64
            base: ghcr.io/home-assistant/amd64-base-debian:trixie
          - arch: aarch64
            platform: linux/arm64
            base: ghcr.io/home-assistant/aarch64-base-debian:trixie
          - arch: armv7
            platform: linux/arm/v7
            base: ghcr.io/home-assistant/armv7-base-debian:trixie

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Derive version from add-on config
        id: meta
        run: |
          VERSION=$(grep -E '^version:' internet_health_checker/config.yaml | awk '{print $2}')
          if [ -z "$VERSION" ]; then echo "version not found"; exit 1; fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ matrix.arch }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: internet_health_checker/Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          build-args: |
            BUILD_FROM=${{ matrix.base }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/internet_health_checker-${{ matrix.arch }}:${{ steps.meta.outputs.version }}
            ghcr.io/${{ github.repository_owner }}/internet_health_checker-${{ matrix.arch }}:latest
